app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/abhilashgd
      password: 'password'
      pool-size: 30
      username: abhilashgd

server:
  error:
    include-binding-errors: always
    include-message: always


